repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        files: ^.*\.(py|md|yaml|js|ts|ipynb)$
        args: ["--skip=**/solara_portal/**"]
        additional_dependencies:
          - tomli
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
        args: ["--no-fix"]
        stages: [commit]
      - id: ruff-format
        args: ["--check"]
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        pass_filenames: false
        args: [--no-strict-optional, --ignore-missing-imports, --explicit-package-bases, --check-untyped-defs, .]
        additional_dependencies: [types-requests, types-markdown, types-PyYAML, types-filelock, types-cachetools, types-redis, reacton, types-six, types-decorator]
        exclude: tests/unit/solara_test_apps/multipage/04-a_directory/*
