[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"



[project]
name = "solara"
authors = [{name = "Maarten A. Breddels", email = "maartenbreddels@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
packages = [
    { include = "solara" }
]
dependencies = [
    "react-ipywidgets",
    "diskcache",
    "markdown",
    "pygments",
    "pymdown-extensions",
    "markdown-it-py",
    "mdit-py-plugins",
    "humanize"
]

[tool.flit.module]
name = "solara"



[project.optional-dependencies]
dev = [
    "pyproject-flake8",
    "flake8",
    "black",
    "mypy",
    "playwright",
    "pytest-playwright",

]
server = [
    "click",
    "rich_click",
    "uvicorn",
    "watchgod",
    "websockets",
    "fastapi",
    "voila",
]
examples = [
    "bqplot",
    "altair",
    "vega_datasets",
    "plotly",
]

[project.urls]
Home = "https://www.github.com/widgetti/solara"

[project.scripts]
solara = "solara.__main__:main"

[tool.black]
line-length = 160

[tool.isort]
profile = "black"


[tool.pytest.ini_options]
addopts = "--disable-warnings --screenshot=only-on-failure"
timeout = 5
